import z from "zod";
import { apiProductRequestLogSelectAllZod, openapiRequestInputZod } from "./api_product_request_log.zod.js";
import { zSmallint, zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

export const journalEntryMandatoryZod = z.object({
	content: zString
		.min(1, "Please write at least 1 character to save your entry")
		.max(50000, "Your entry is too long. Maximum 50,000 characters allowed"),
	authorUserId: z.uuid(),
	// Main file & Thumbnail
	attachmentUrls: z.array(z.tuple([z.url(), z.url().or(z.literal("not-available"))])).default([])
});

export const journalEntryAutoGeneratedZod = z.object({
	journalEntryId: z.ulid(),
});

export const journalEntryOptionalZod = z.object({
	prompt: zString.max(500).nullable(),
	promptId: zSmallint(1).nullable(),
	deletedAt: zTimeEpoch.nullable(),
	teamId: z.uuid().nullable().default(null),
});

export const journalEntryCreateInputZod = journalEntryMandatoryZod
	.omit({ authorUserId: true })
	.extend(journalEntryOptionalZod.partial().shape)
	.extend({
		journalEntryId: journalEntryAutoGeneratedZod.shape.journalEntryId
	});
export type JournalEntryCreateInput = z.infer<typeof journalEntryCreateInputZod>;



export const pendingSyncJournalEntryZod = journalEntryCreateInputZod
  .omit({ attachmentUrls: true })
  .extend({
    createdAt: zTimeEpoch,
    status: z.enum(["file-upload-pending", "file-upload-in-progress", "file-upload-completed", "file-upload-failed", "syncing", "synced", "sync-failed"]),
    error: z.string().optional(),
    errorCount: zSmallint(0).default(0),
    attachmentFileIds: z.array(z.ulid()).default([]),
  });

export type PendingSyncJournalEntry = z.infer<typeof pendingSyncJournalEntryZod>;

export const journalEntryUpdateInputZod = z.object({
	journalEntryId: z.ulid(),
	content: zString
		.min(1, "Please write at least 1 character to save your entry")
		.max(50000, "Your entry is too long. Maximum 50,000 characters allowed")
		.optional(),
	prompt: zString.max(500).nullable().optional(),
});
export type JournalEntryUpdateInput = z.infer<typeof journalEntryUpdateInputZod>;

export const journalEntryUpdateWithTeamInputZod = journalEntryUpdateInputZod.extend({
	teamId: z.uuid().nullable().optional(),
});
export type JournalEntryUpdateWithTeamInput = z.infer<typeof journalEntryUpdateWithTeamInputZod>;

export const journalEntrySelectAllZod = journalEntryMandatoryZod.extend(journalEntryOptionalZod.shape).extend(zTimestamps).extend(journalEntryAutoGeneratedZod.shape);
export type JournalEntrySelectAll = z.infer<typeof journalEntrySelectAllZod>;

/** @alias */
export const journalEntryGetByIdZod = journalEntryAutoGeneratedZod;
export type GetJournalEntryByIdInput = z.infer<typeof journalEntryGetByIdZod>;

export const journalEntryGetByUserZod = z.object({
	authorUserId: z.uuid(),
});
export type GetJournalEntriesByUserInput = z.infer<typeof journalEntryGetByUserZod>;

/** @alias */
export const journalEntryDeleteZod = journalEntryAutoGeneratedZod
export type DeleteJournalEntryInput = z.infer<typeof journalEntryDeleteZod>;

export const openapiJournalEntryCreateInputZod = openapiRequestInputZod.extend({
	data: journalEntryCreateInputZod
});
export type OpenapiJournalEntryCreateInputZod = z.infer<typeof openapiJournalEntryCreateInputZod>;

export const openapiJournalEntryCreateResponseOutputZod = apiProductRequestLogSelectAllZod.extend({
	responseJson: journalEntrySelectAllZod.nullable()
})