import { z } from "zod";
import { zString, zTimestamps, zTimeEpoch, zPhoneNumber } from "./zod_utils.js";

export const leadMandatoryZod = z.object({
	contactName: zString.min(1, "Contact name is required").max(255),
	capturedByUserId: z.uuid(),
});

export const leadOptionalZod = z.object({
	companyName: zString.max(255).nullable(),
	jobTitle: zString.max(255).nullable(),
	email: z.string().email("Invalid email").max(255).nullable(),
	phone: zPhoneNumber.nullable(),
	website: z.string().url("Invalid URL").max(255).nullable(),
	address: zString.max(500).nullable(),
	notes: zString.max(5000).nullable(),
	teamId: z.uuid().nullable(),
	deletedAt: zTimeEpoch.nullable(),
});

export const leadAutoGeneratedZod = z.object({
	leadId: z.ulid(),
});

export const leadCreateInputZod = leadMandatoryZod
	.omit({ capturedByUserId: true })
	.extend(leadOptionalZod.partial().shape)
	.omit({ deletedAt: true });

export type LeadCreateInput = z.infer<typeof leadCreateInputZod>;

export const leadUpdateInputZod = leadMandatoryZod
	.extend(leadOptionalZod.shape)
	.extend(zTimestamps)
	.partial()
	.omit({ deletedAt: true });

export type LeadUpdateInput = z.infer<typeof leadUpdateInputZod>;

export const leadSelectAllZod = leadMandatoryZod
	.extend(leadOptionalZod.shape)
	.extend(zTimestamps)
	.extend(leadAutoGeneratedZod.shape);

export type LeadSelectAll = z.infer<typeof leadSelectAllZod>;

export const leadGetByIdZod = leadAutoGeneratedZod;
export type GetLeadByIdInput = z.infer<typeof leadGetByIdZod>;

export const leadDeleteZod = leadAutoGeneratedZod;
export type DeleteLeadInput = z.infer<typeof leadDeleteZod>;
