import z from "zod";
import { apiProductSkuZod } from "./enums.zod.js";
import { zSmallint, zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

const subscriptionAutoGeneratedZod = z.object({
  subscriptionId: z.ulid(),
});

const subscriptionMandatoryZod = z.object({
  expiresAt: zTimeEpoch,
  maxRequests: zSmallint(0),
  apiProductSku: apiProductSkuZod,
  apiProductQuantity: zSmallint(1),
  requestsConsumed: zSmallint(0).default(0),
  teamId: z.uuid(),
  teamUserReferenceId: zString,
});

const subscriptionOptionalZod = z.object({
  billingInvoiceNumber: zString.nullable(),
  billingInvoiceDate: zTimeEpoch.nullable(),
  notifiedAt90PercentUse: zTimeEpoch.nullable(),
  paymentReceivedDate: zTimeEpoch.nullable(),
  paymentTransactionId: zString.nullable(),
});

export const subscriptionCreateInputZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.partial().shape);
export type SubscriptionCreateInput = z.infer<typeof subscriptionCreateInputZod>;

export const subscriptionUpdateInputZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.shape).extend(zTimestamps).partial();
export type SubscriptionUpdateInput = z.infer<typeof subscriptionUpdateInputZod>;

export const subscriptionSelectAllZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.shape).extend(subscriptionAutoGeneratedZod.shape).extend(zTimestamps);
export type SubscriptionSelectAll = z.infer<typeof subscriptionSelectAllZod>;

export const subscriptionGetByIdInputZod = subscriptionAutoGeneratedZod;
export type SubscriptionGetByIdInput = z.infer<typeof subscriptionGetByIdInputZod>;

export const subscriptionGetActiveByTeamUserZod = z.object({
  teamUserReferenceId: z.string(),
  apiProductSku: apiProductSkuZod.optional(),
});
export type SubscriptionGetActiveByTeamInput = z.infer<typeof subscriptionGetActiveByTeamUserZod>;

export const subscriptionApiCreateInputZod = subscriptionCreateInputZod.pick({
  apiProductSku: true,
  apiProductQuantity: true,
  teamUserReferenceId: true,
});
export type SubscriptionApiCreateInput = z.infer<typeof subscriptionApiCreateInputZod>;

export const subscriptionsUpdateBillingDetailZod = subscriptionUpdateInputZod.pick({
  billingInvoiceNumber: true,
  billingInvoiceDate: true,
}).extend({
  subscriptionIds: z.array(subscriptionAutoGeneratedZod.shape.subscriptionId),
});
export type SubscriptionUpdateBillingDetails = z.infer<typeof subscriptionsUpdateBillingDetailZod>;

export const subscriptionsUpdatePaymentDetailZod = subscriptionUpdateInputZod.pick({
  paymentReceivedDate: true,
  paymentTransactionId: true,
}).extend({
  subscriptionIds: z.array(subscriptionAutoGeneratedZod.shape.subscriptionId),
});
export type SubscriptionUpdatePaymentDetails = z.infer<typeof subscriptionsUpdatePaymentDetailZod>;

export const subscriptionsCancelInputZod = z.object({
  subscriptionIds: z.array(subscriptionAutoGeneratedZod.shape.subscriptionId),
});
export type SubscriptionCancelInput = z.infer<typeof subscriptionsCancelInputZod>;