import z from "zod";
import { teamMemberRoleZod } from "./enums.zod.js";
import { zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

/**
 * TeamApp Schemas
 */

export const teamAppAutoGeneratedZod = z.object({
  teamAppId: z.uuid(),
});

export const teamAppMandatoryZod = z.object({
  name: zString.min(1, "Team name is required"),
});

export const teamAppOptionalZod = z.object({
  logoUrl: zString.nullable(),
  createdByUserId: z.uuid(),
  deletedAt: zTimeEpoch.nullable(),
});

export const teamAppCreateInputZod = teamAppMandatoryZod.extend(teamAppOptionalZod.partial().shape);
export type TeamAppCreateInput = z.infer<typeof teamAppCreateInputZod>;

export const teamAppSelectAllZod = teamAppMandatoryZod
  .extend(teamAppOptionalZod.shape)
  .extend(teamAppAutoGeneratedZod.shape)
  .extend(zTimestamps);
export type TeamAppSelectAll = z.infer<typeof teamAppSelectAllZod>;

/**
 * TeamMember Schemas
 */

export const teamAppMemberAutoGeneratedZod = z.object({
  teamMemberId: z.uuid(),
});

export const teamAppMemberMandatoryZod = z.object({
  teamAppId: z.uuid(),
  role: teamMemberRoleZod,
  addedAt: zTimeEpoch,
});

export const teamAppMemberOptionalZod = z.object({
  userId: z.uuid().nullable(),
  email: zString.nullable(),
  joinedAt: zTimeEpoch.nullable(),
  deletedAt: zTimeEpoch.nullable(),
});

export const teamAppMemberSelectAllZod = teamAppMemberMandatoryZod
  .extend(teamAppMemberOptionalZod.shape)
  .extend(teamAppMemberAutoGeneratedZod.shape)
  .extend(zTimestamps);
export type TeamAppMemberSelectAll = z.infer<typeof teamAppMemberSelectAllZod>;

export const teamAppMemberRoleZod = teamMemberRoleZod;
export type TeamAppMemberRole = z.infer<typeof teamAppMemberRoleZod>;

export const teamWithRoleZod = teamAppSelectAllZod.extend({
  userRole: teamMemberRoleZod,
});
export type TeamWithRole = z.infer<typeof teamWithRoleZod>;