import { z } from "zod";
import { apiProductSkuZod } from "./enums.zod.js";
import { zSmallint, zString, zTimestamps } from "./zod_utils.js";

const teamApiAutoGeneratedZod = z.object({
  teamApiId: z.uuid(),
});

const teamApiMandatoryZod = z.object({
  allowApiSubsCreationForSkus: z.array(apiProductSkuZod).default([]),
  allowedDomains: z.array(zString).default([]),
  allowedIPs: z.array(zString).default([]),
  apiSecretHash: zString,
  name: zString,
  rateLimitPerMinute: zSmallint(),
});

const teamApiOptionalZod = z.object({
  subscriptionAlertWebhookUrl: z.url().nullable(),
  subscriptionAlertWebhookBearerToken: zString.nullable(),
});

export const teamApiCreateInputZod = teamApiMandatoryZod.extend(teamApiOptionalZod.partial().shape)
  .omit({
    apiSecretHash: true,
  })
  .extend({
    apiSecretKey: zString.min(1, "API Secret Key is required")
  });
export type TeamApiCreateInput = z.infer<typeof teamApiCreateInputZod>;

export const teamApiUpdateInputZod = teamApiMandatoryZod
  .extend(teamApiOptionalZod.shape)
  .extend(teamApiAutoGeneratedZod.shape)
  .extend(zTimestamps)
  .omit({
    apiSecretHash: true,
    rateLimitPerMinute: true,
    subscriptionAlertWebhookBearerToken: true,
  })
  .partial();
export type TeamApiUpdateInput = z.infer<typeof teamApiUpdateInputZod>;

export const teamApiSelectAllZod = teamApiMandatoryZod
  .extend(teamApiOptionalZod.shape)
  .extend(teamApiAutoGeneratedZod.shape)
  .extend(zTimestamps)
  .omit({
    apiSecretHash: true,
    subscriptionAlertWebhookBearerToken: true,
  });
export type TeamApiSelectAll = z.infer<typeof teamApiSelectAllZod>;

export const teamApiGetByIdInputZod = teamApiAutoGeneratedZod;