import { z } from "zod";
import { teamMemberRoleZod } from "./enums.zod.js";
import { zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

/**
 * TeamApp Schemas
 */

export const teamAppAutoGeneratedZod = z.object({
  id: z.ulid(),
});

export const teamAppMandatoryZod = z.object({
  name: zString.min(1, "Team name is required"),
});

export const teamAppOptionalZod = z.object({
  logoUrl: zString.nullable(),
  createdByUserId: z.uuid(),
  personalTeamForUserId: z.uuid().nullable(),
  deletedAt: zTimeEpoch.nullable(),
});

export const teamAppCreateInputZod = teamAppMandatoryZod.extend(teamAppOptionalZod.partial().shape);
export type TeamAppCreateInput = z.infer<typeof teamAppCreateInputZod>;

export const teamAppSelectAllZod = teamAppMandatoryZod
  .extend(teamAppOptionalZod.shape)
  .extend(teamAppAutoGeneratedZod.shape)
  .extend(zTimestamps);
export type TeamAppSelectAll = z.infer<typeof teamAppSelectAllZod>;

/**
 * TeamMember Schemas
 */

export const teamAppMemberAutoGeneratedZod = z.object({
  id: z.ulid(),
});

export const teamAppMemberMandatoryZod = z.object({
  teamId: z.ulid(),
  role: teamMemberRoleZod,
  addedAt: zTimeEpoch,
});

export const teamAppMemberOptionalZod = z.object({
  userId: z.uuid().nullable(),
  email: zString.nullable(),
  phoneNumber: zString.nullable(),
  joinedAt: zTimeEpoch.nullable(),
  deletedAt: zTimeEpoch.nullable(),
});

export const teamAppMemberSelectAllZod = teamAppMemberMandatoryZod
  .extend(teamAppMemberOptionalZod.shape)
  .extend(teamAppMemberAutoGeneratedZod.shape)
  .extend(zTimestamps);
export type TeamAppMemberSelectAll = z.infer<typeof teamAppMemberSelectAllZod>;

export const teamAppMemberRoleZod = teamMemberRoleZod;
export type TeamAppMemberRole = z.infer<typeof teamAppMemberRoleZod>;

export const teamAppMemberAddInputZod = z.object({
  teamId: z.ulid(),
  email: z.email().optional().nullable(),
  phoneNumber: zString.optional().nullable(),
  role: teamMemberRoleZod,
}).refine(data => data.email || data.phoneNumber, {
  message: "Either email or phone number must be provided",
  path: ["email"],
});
export type TeamAppMemberAddInput = z.infer<typeof teamAppMemberAddInputZod>;

export const teamWithRoleZod = teamAppSelectAllZod.extend({
  joinedAt: zTimeEpoch.nullable(),
  userRole: teamMemberRoleZod,
});
export type TeamWithRole = z.infer<typeof teamWithRoleZod>;