import z from "zod";
import { zString, zTimestamps } from "./zod_utils.js";

export const teamAutoGeneratedZod = z.object({
  teamId: z.uuid(),
});

export const teamMandatoryZod = z.object({
  name: zString.min(1, "Team name is required").max(100),
  createdByUserId: z.uuid(),
});

export const teamOptionalZod = z.object({
  logoUrl: z.url().nullable(),
});

export const teamCreateInputZod = teamMandatoryZod
	.omit({ createdByUserId: true })
	.extend(teamOptionalZod.partial().shape);
export type TeamCreateInput = z.infer<typeof teamCreateInputZod>;

export const teamUpdateInputZod = teamMandatoryZod
  .extend(teamOptionalZod.shape)
  .extend(teamAutoGeneratedZod.shape)
  .extend(zTimestamps)
  .partial();
export type TeamUpdateInput = z.infer<typeof teamUpdateInputZod>;

export const teamSelectAllZod = teamMandatoryZod
  .extend(teamOptionalZod.shape)
  .extend(teamAutoGeneratedZod.shape)
  .extend(zTimestamps);
export type TeamSelectAll = z.infer<typeof teamSelectAllZod>;

export const teamGetByIdInputZod = teamAutoGeneratedZod;

export const teamMemberRoleZod = z.enum(["owner", "admin", "user"]);
export type TeamMemberRole = z.infer<typeof teamMemberRoleZod>;

export const teamMemberSelectAllZod = z.object({
	teamMemberId: z.ulid(),
	teamId: z.uuid(),
	userId: z.uuid().nullable(),
	email: z.string().email(),
	role: teamMemberRoleZod,
	joinedAt: z.number().nullable(),
}).extend(zTimestamps);
export type TeamMemberSelectAll = z.infer<typeof teamMemberSelectAllZod>;

export const teamWithRoleZod = teamSelectAllZod.extend({
	userRole: teamMemberRoleZod,
});
export type TeamWithRole = z.infer<typeof teamWithRoleZod>;
