import { themeSettingZod } from "@zod-schemas/enums.zod.js";
import { z } from "zod";
import { teamAppSelectAllZod } from "./team_app.zod.js";
import { uniqueTimeArrayZod, zString, zTimestamps, zTimezone } from "./zod_utils.js";

export const userMandatoryZod = z.object({
  name: zString,
  themeSetting: themeSettingZod.default("system"),
  timezone: zTimezone.default("Etc/UTC"),
	journalReminderTimes: uniqueTimeArrayZod
});

const userAutoGeneratedZod = z.object({
  id: z.uuid(),
  emailVerified: z.boolean(),
  phoneNumberVerified: z.boolean().default(false),
});

export const userOptionalZod = z.object({
  email: z.email().nullable(),
  phoneNumber: zString.nullable(),
  image: z.url().nullable(),
  activeTeamAppId: z.string().nullable(),
});

export const userCreateInputZod = userMandatoryZod.extend(userOptionalZod.partial().shape);
export type UserCreateInput = z.infer<typeof userCreateInputZod>;

export const userUpdateInputZod = userMandatoryZod.extend(userOptionalZod.shape).extend(zTimestamps).omit({ email: true }).partial();
export type UserUpdateInput = z.infer<typeof userUpdateInputZod>;

export const userSelectAllZod = userMandatoryZod.extend(userOptionalZod.shape).extend(zTimestamps).extend(userAutoGeneratedZod.shape);
export type UserSelectAll = z.infer<typeof userSelectAllZod>;

export const userGetByIdInputZod = userAutoGeneratedZod;
export type UserGetByIdInput = z.infer<typeof userGetByIdInputZod>;

export const userWithTeamsZod = userSelectAllZod.extend({
	teams: z.array(teamAppSelectAllZod)
});
export type UserWithTeams = z.infer<typeof userWithTeamsZod>;
